config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#root'

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  get "/auth/:provider/callback", to: "sessions#omniauth"

  namespace :api, defaults: { format: :json } do
    #resource :current_user, only: [:show]
    resource :session, only: [:show]
    resources :users, only: [:index, :show, :update]
    resources :projects, except: [:new, :edit] do
      resources :users, only: [:index]
      resources :collaborations, only: [:create]
    end
    resources :todo_lists, only: [:show, :create, :update, :destroy] do
      resources :todo_items, only: [:index]
    end
    resources :todo_items, only: [:show, :create, :update, :destroy]
    resources :discussions, only: [:show, :update, :destroy, :create]
    resources :comments, only: [:create, :update, :destroy]
    resources :collaborations, only: [:destroy]
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :require_login!

  def root
    redirect_to new_session_url unless logged_in?
  end
end

app/views/static_pages/_header.html.erb
<header class="root-header">
  <nav class="group">
    <ul class="main-header">
      <li><a href="#">
        <img class="root-logo" src="https://s3.amazonaws.com/spacecamp-static-images/SpaceCamp-logo.png" alt="SpaceCamp Logo"></a>
      </li>
      <li class="all-projects"><a href="#">All Projects</a></li>
    </ul>
    <section class="user-info">
      <li><img src="<%= current_user.avatar.url(:thumb) %>"></li>
      <ul>
        <li class="header-name"><%= current_user.fname %> <%= current_user.lname %></li>
        <li><%= render "logout_button" if logged_in? %></li>
      </ul>
    </section>
  </nav>
</header>

app/views/static_pages/_logout_button.html.erb
<form class="logout-button" action="<%= session_url %>" method="post">
  <input type="hidden" name="_method" value="delete">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <button>Sign out</button>
</form>

app/views/static_pages/root.html.erb
<%= render "header" if logged_in? %>
<section id="content"></section>

<script>$(document).ready(function(){
  SpaceCamp.initialize();
});
</script>