config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#root'

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  get "/auth/:provider/callback", to: "sessions#omniauth"

  namespace :api, defaults: { format: :json } do
    #resource :current_user, only: [:show]
    resource :session, only: [:show]
    resources :users, only: [:index, :show, :update]
    resources :projects, except: [:new, :edit] do
      resources :users, only: [:index]
      resources :collaborations, only: [:create]
    end
    resources :todo_lists, only: [:show, :create, :update, :destroy] do
      resources :todo_items, only: [:index]
    end
    resources :todo_items, only: [:show, :create, :update, :destroy]
    resources :discussions, only: [:show, :update, :destroy, :create]
    resources :comments, only: [:create, :update, :destroy]
    resources :collaborations, only: [:destroy]
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                  :integer          not null, primary key
#  email               :string           not null
#  fname               :string           not null
#  lname               :string           not null
#  password_digest     :string           not null
#  session_token       :string           not null
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  avatar_file_name    :string
#  avatar_content_type :string
#  avatar_file_size    :integer
#  avatar_updated_at   :datetime
#  provider            :string
#  uid                 :string
#

class User < ActiveRecord::Base

  attr_reader :password

  validates :email, :fname, :lname, :password_digest, :session_token, presence: true
  validates :email, :session_token, uniqueness: true
  validates :password, length: { minimum: 6 }, allow_nil: true

  has_attached_file :avatar, default_url: "appacademylogo.png", styles: {
    medium: "100x100>",
    thumb: "60x60>"
  }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  after_initialize :ensure_session_token!

  has_many(
    :collaborations,
    class_name: 'Collaboration',
    foreign_key: :user_id
  )

  has_many(
    :projects,
    through: :collaborations,
    source: :project
  )

  has_many(
    :owned_projects,
    class_name: "Project",
    foreign_key: :owner_id
  )

  has_many(
    :owned_project_collaborations,
    through: :owned_projects,
    source: :collaborations
  )

  has_many(
    :to_do_lists,
    through: :projects,
    source: :to_do_lists
  )

  has_many(
    :to_do_items,
    through: :projects,
    source: :to_do_items
  )

  has_many(
    :authored_discussions,
    class_name: "Discussion",
    foreign_key: :author_id
  )

  has_many(
    :authored_comments,
    class_name: "Comment",
    foreign_key: :author_id
  )

  has_many(
    :discussions,
    through: :projects,
    source: :discussions
  )

  has_many(
    :comments,
    through: :discussions,
    source: :comments
  )

  has_many(
    :assigned_to_do_items,
    class_name: 'ToDoItem',
    foreign_key: :assigned_user_id
  )

  def self.find_or_create_by_auth_hash(auth_hash)
    user = User.find_by(
            provider: auth_hash[:provider],
            uid: auth_hash[:uid])

    unless user
      user = User.find_by(email: auth_hash[:info][:email])
      if user
        user.update!(
          provider: auth_hash[:provider],
          uid: auth_hash[:uid]
        )
      else
        user = User.create!(
              provider: auth_hash[:provider],
              uid: auth_hash[:uid],
              fname: auth_hash[:info][:name].split.first,
              lname: auth_hash[:info][:name].split.last,
              email: auth_hash[:info][:email],
              password: SecureRandom::urlsafe_base64
        )
      end
    end

    user
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return unless user

    user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end

  def reset_token!
    self.update(session_token: User.generate_session_token)
    self.session_token
  end


  private

  def ensure_session_token!
    self.session_token ||= User.generate_session_token
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  wrap_parameters false

  def index
    @users = User.all
  end

  def show
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      render json: @user
    else
      render json: @user.errors.full_messages, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:fname, :lname, :avatar)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :require_login!, only: [:new, :create]

  wrap_parameters false

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      redirect_to root_url
    else
      flash.now[:errors] = "Invalid user information"
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @projects = Project.where(owner_id: @user.id)

  end

  private

  def user_params
    params.require(:user).permit(:email, :fname, :lname, :password, :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<section id="sign-up-page">
  <div class="transparent-background">
    <h1>Sign Up</h1>
  </div>

  <form enctype="multipart/form-data" class="new-user" action="<%= users_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input class="email"
           type="text"
           name="user[email]"
           value="<%= @user.email %>"
           placeholder="Email Address">
    <input class="fname"
           type="text"
           name="user[fname]"
           value="<%= @user.fname %>"
           placeholder="First Name">
    <input class="lname"
           type="text"
           name="user[lname]"
           value="<%= @user.lname %>"
           placeholder="Last Name">
    <input class="password"
           type="password"
           name="user[password]"
           placeholder="Password">
    <input class="avatar"
           type="file"
           name="user[avatar]">
    <img class="preview-avatar" src="" width="50">
    <button class="new-user-button">Submit</button>
  </form>
  <br>
  <a class="sign-in-link" href="<%= new_session_url %>">Sign In</a>
</section>

app/views/users/show.html.erb
<h1><%= @user.fname %> <%= @user.lname %></h1>
<br>
<a href="<%= new_project_url %>">Create New Project</a>
<br>
<% @projects.each do |project| %>
  <h1><a href="<%= project_url(project.id) %>"><%= project.title %></a></h1>
  <p>
    <%= project.description %>
  </p>
  <br>
<% end %>