config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#root'

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  get "/auth/:provider/callback", to: "sessions#omniauth"

  namespace :api, defaults: { format: :json } do
    #resource :current_user, only: [:show]
    resource :session, only: [:show]
    resources :users, only: [:index, :show, :update]
    resources :projects, except: [:new, :edit] do
      resources :users, only: [:index]
      resources :collaborations, only: [:create]
    end
    resources :todo_lists, only: [:show, :create, :update, :destroy] do
      resources :todo_items, only: [:index]
    end
    resources :todo_items, only: [:show, :create, :update, :destroy]
    resources :discussions, only: [:show, :update, :destroy, :create]
    resources :comments, only: [:create, :update, :destroy]
    resources :collaborations, only: [:destroy]
  end
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id          :integer          not null, primary key
#  owner_id    :integer          not null
#  title       :string           not null
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Project < ActiveRecord::Base

  validates :owner_id, :title, presence: true

  belongs_to(
    :owner,
    class_name: "User",
    foreign_key: :owner_id
  )

  has_many :collaborations

  has_many :to_do_lists

  has_many :discussions

  has_many(
    :to_do_items,
    through: :to_do_lists,
    source: :to_do_items
  )

  has_many(
    :collaborators,
    through: :collaborations,
    source: :user
  )

end

app/controllers/api/projects_controller.rb
class Api::ProjectsController < ApplicationController
  def index
    @projects = current_user.projects
    render :index
  end

  def show
    @project = current_user.projects.find(params[:id])
    render :show
  end

  def create
    @project = current_user.owned_projects.new(project_params)
    if @project.save
      create_owner_collaboration(@project.id, current_user.id)
      render json: @project
    else
      render json: @project.errors.full_messages, status: :unprocessable_entity
    end
  end

  private

  def project_params
    params.require(:project).permit(:title, :description)
  end

  def create_owner_collaboration(project_id, user_id)
    @collaboration = Collaboration.new(
      project_id: project_id,
      user_id: user_id
    )
    @collaboration.save
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.where(owner_id: current_user.id)
  end

  def show
    @project = Project.find(params[:id])
    if @project.owner_id == current_user.id
      render :show
    else
      redirect_to user_url(current_user)
    end
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.owner_id = current_user.id
    if @project.save
      redirect_to project_url(@project)
    else
      flash.now[:errors] = "Invalid project information"
      render :new
    end
  end

  private

  def project_params
    params.require(:project).permit(:title, :description)
  end

end

app/views/projects/new.html.erb
<h1>New Project</h1>
<a href="<%= user_url(current_user) %>">Back to All Projects</a>
<br>
<br>
<form class="new-project" action="<%= projects_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="title">Title</label>
  <input id="title" type="text" name="project[title]" value="<%= @project.title %>">
  <br>
  <label for="description">Description</label>
  <textarea id="description"
            name="project[description]"
            rows="8"
            cols="40"><%= @project.description %></textarea>
  <br>
  <button class="new-project-button">Create</button>
</form>

app/views/projects/show.html.erb
<br>
<a href="<%= user_url(current_user) %>">Back to All Projects</a>
<br>
<h1><%= @project.title %></h1>
<p>
  <%= @project.description %>
</p>